---
  - src: git@github.com:boakaa24/boakaa24/java_role.git
    scm: git
    version: "1.0.1"
    name: java
  - src: git@github.com:boakaa24/elastic_role.git
    scm: git
    version: "1.0.1"
    name: elastic
  - src: git@github.com:boakaa24/kibana_role.git
    scm: git
    version: "1.0.1"
    name: kibana
